### ISSUE TITLE
COSMIC Dock does not show after locking the screen

### ISSUE THREAD

**Issue by isantop** [pop-os/cosmic-dock#125]
After locking the screen and logging back in, the dock is no longer shown. In order to re-show the dock, GNOME Shell must be restarted (Alt+F2, r)

**Comment by 13r0ck** [comment]
Are you still seeing this on the newest version of jammy? I was unable to reproduce this

**Comment by smiggiddy** [comment]
I'm experiencing this issue

**Comment by leviport** [comment]
@smiggiddy Are you running 22.04?

**Comment by hanna-brooks** [comment]
I am having the same problem.

## Steps to Reproduce

1. Start a gnome session (reboot, login, alt-f2 'r')
  
2. Lock screen using keyboard shortcut or gnome menu

3. Unlock the screen using gnome login

restarting the gnome session after log-in, rebooting or logging out and logging back in will all return the behavior of the cosmic dock to normal

## Expected Behavior

Dock appears on left hand side of screen (as configured in settings) with intelligent autohide (as configured in settings).

![workingDock](https://user-images.githubusercontent.com/63319975/164934307-2ee01284-e874-4f4a-a89c-25dbdb8a82cc.png)

## Actual Behavior

1. cosmic dock is missing (does not appear when set to always show or intelligently autohide)
  
2. Dock appears with gnome 42 defaults at the bottom of the screen in activities view, but is not functional.
  
![notworkingDock](https://user-images.githubusercontent.com/63319975/164934313-21fee5c3-c083-427d-9bec-20263474d8f7.png)


## Context

Manjaro system with gnome 42 on wayland. Pop-cosmic and gnome-control-center-cosmic installed with dependencies.

Does not happen on a S76 Lemur Pro running PopOS

### Warnings about *dash-item-container* and *_revertPanelCorners*co-occur

```bash
Failed to destroy dockManager: this._revertPanelCorners is not a function
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
st_widget_get_theme_node called on the widget [0x5606c3a68c90 Gjs_cosmic-dock_system76_com_appIcons_DockShowAppsIcon.dash-item-container] which is not in the stage.
Failed to destroy dockManager: this._revertPanelCorners is not a function
```

Maybe this has to do with *docking.js*:
[this._revertPanelCorners();](https://github.com/pop-os/cosmic-dock/blob/404e4f264c71de44f4b586b0aef4ce7ac643a925/docking.js#L2246)

**Comment by hanna-brooks** [comment]
I removed pop-cosmic and gnome-control-center-cosmic and dependencies, replaced with gnome-control-center and gnome-shell-extension-dash-to-dock-git, to test to see if this is an issue with DashToDock on Gnome42.

I was not able to replicate the issue with similar settings (left dock, intelligent auto-hide) on DashToDock after locking the screen and returning to the session.

The warnings about dash-item-container and _revertPanelCorners did not occur with DashToDock without pop-cosmic and cosmic-dock.

**Comment by camden-bock** [comment]
I was able to replicate this issue on a Manjaro system with AMD graphics after updating to Gnome 42 with Kernel 5.15. 

No issue on Gnome 41.

**Comment by camden-bock** [comment]
philm at Manjaro forums notes that the Gnome 42 update breaks COSMIC on Manjaro. [Manjaro Forums](https://forum.manjaro.org/t/unstable-update-2022-04-07-gnome-42-mesa-22-0-1-octopi-0-13-0-kde-git-haskell/107784)

> Manjaro COSMIC status
> For those using the Manjaro COSMIC packages, you will need to remove them. I’ve dropped them from the repos. Once  System76 finishes their new Gtk 4 applications for Pop!_OS, I’ll see about adding them.

**Comment by camden-bock** [comment]
> philm at Manjaro forums notes that the Gnome 42 update breaks COSMIC on Manjaro. [Manjaro Forums](https://forum.manjaro.org/t/unstable-update-2022-04-07-gnome-42-mesa-22-0-1-octopi-0-13-0-kde-git-haskell/107784)
> 
> > Manjaro COSMIC status
> > For those using the Manjaro COSMIC packages, you will need to remove them. I’ve dropped them from the repos. Once  System76 finishes their new Gtk 4 applications for Pop!_OS, I’ll see about adding them.

**Comment by 13r0ck** [comment]
GNOME 42 is not compatible with the old cosmic extensions. As such they have been updated and are available in the `master_jammy` branch of this repository.
COSMIC does not work on GNOME 42, as Pop!_OS releases with gnome 42 tomorrow.

As well this issue is not present in Pop!_OS 22.04, please upgrade your systems tomorrow when 22.04 is released.
