### ISSUE TITLE
Issues on GNOME 40

### ISSUE THREAD

**Issue by DarkPhoenix645** [pop-os/cosmic-dock#38]
I know this is a fork of the dash to dock extension and thus might not support GNOME 40 right now. If this is the case, please add GNOME 40 support as soon as possible. Here is the error and stack trace shown in GNOME extensions -
Error:
```
TypeError: box.add is not a function
```

Stack trace:
```
buildPrefsWidget@/home/nilanjan/.local/share/gnome-shell/extensions/cosmic-dock@system76.com/prefs.js:32:9
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by CosmicFusion** [comment]
as you said the cosmic dock is based on dash to dock which is only compatible with gnome 3.38 and earlier because all though gnome 40 and 3.38 look really similar under the hood its a really different DE (GTK 4)   which means if system76 wanted to port it to gnome 40 they are gonna have to re invent the wheel but someone has all ready did this but its not a polished experience  and only supports X11 by default https://github.com/ewlsh/dash-to-dock

**Comment by DarkPhoenix645** [comment]
Thank you for telling me about that branch in dash to dock. It works like a charm (for me at least). I'll use that until an official release comes out.
